### ISSUE TITLE
Problem in fix_bond_propagate_gran.cpp:125

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [schrummy14/LIGGGHTS_Flexible_Fibers#1]
I am using your code to run a study case and I receive this error:

ERROR on proc 0: Failed to operate on granular bond history during copy i2 (../fix_bond_propagate_gran.cpp:125)

What can I do to resolve the issue?

I did some improvement in the code too and would like to share it with you.

Thank you very much.

**Comment by schrummy14** [comment]
Hello,
Sorry for the error you are receiving.
Could you send me your input file or an equivalent input file? The error by
itself does not give me much to go on.

The error indicates that the bond cannot find its pair of spheres. This can
only happen if you are using newton_bond (I have not tested this) or if
both spheres are on the same processor.

**Comment by DanielBorgesOliveira** [comment]
Bellow is file of the simulation.

[example.tar.gz](https://github.com/schrummy14/LIGGGHTS_Flexible_Fibers/files/3623921/example.tar.gz)


I wrote the code in a package form and made some minor modification. Please, if you will run my example use this new source files and recompile LIGGGHTS.

[source_code.tar.gz](https://github.com/schrummy14/LIGGGHTS_Flexible_Fibers/files/3623918/source_code.tar.gz)

I discovery that the error appear if I set the parameter "bond_youngs_modulus" of the command "bond_coeff" above 10e7.  If I set this parameter bellow this value the error disappear.

Thank you very much.

**Comment by schrummy14** [comment]
Hello,
It appears that you are using too large of a timestep. For the bonded model and NO bond damping,
the maximum dt = 1/w = sqrt(m/K) = sqrt((4 r rho lb)/(3 Y)) 
where 
Y = Young's Modulus (Pa)
r = Particle Radius (m)
lb = Bond Length (Equilibrium) 
rho = Particle Density (Kg m^(-3)

Once damping is added, this time step can drop drastically. 
Some testing has shown the empirical relationship (dt <= 1/((1+2.87*beta)*w) 
where beta = local bond damping coefficient that is used. 

dt_ray = 2.5153e-04
For your system (Y_bond = 10e7), it appears that the critical time step is == dt < 2.9664e-04
Y_bond = 10e8 >> dt < 9.3807e-05
Y_bond = 10e9 >> dt < 2.9664e-05
Y_bond = 10e10 >> dt < 9.3807e-06

**Comment by DanielBorgesOliveira** [comment]
Hello,

Looks like this solved the problem.

Thank you very much.
