### ISSUE TITLE
Restart files fail when running cfdem simulations

### ISSUE THREAD

**Issue by schrummy14** [schrummy14/LIGGGHTS_Flexible_Fibers#4]
Tests using restart files are causing particles to disappear after 5 steps. This only happens when coupling with openFOAM and I believe the error is in the coupling files. 
Workaround is to not read in restart files.

**Comment by schrummy14** [comment]
I am currently able to read in my flexible fiber restart files in CFDEM.

**Comment by 3ys** [comment]
In the OpenFOAM and LIGGGHTS coupling simulation, when bond particles reach the boundary of the computational domain, they need to be deleted. However, when the child particles of the bond particles are deleted, an error occurs: "Bond atoms 520 522 missing on proc 39 at step 3111101." How can this be resolved, please?
